ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/<int:p>',views.add_cart,name='addtocart'),
    path('cartview',views.cartview,name='cartview'),
    path('cartremove/<int:p>',views.cart_remove,name='cartremove'),
    path('delete/<int:p>',views.full_remove,name='delete'),
    path('order/',views.orderform,name='order'),
    path('orders/',views.Myorder,name='Myorder')
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls'))
]

ecommerce/search/urls.py
from django.urls import path
from search import views
app_name='search'

urlpatterns = [
    path('/search',views.searchproducts,name='searchproducts'),

]

ecommerce/shop/urls.py
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'

urlpatterns = [
     path('',views.allcategories,name='category1'),
     path('product/<int:n>',views.allproducts,name='products'),
     path('details/<int:n>',views.showdetail,name='details'),
     path('register/',views.register,name='register'),
     path('login/',views.user_login,name='login'),
     path('logout/',views.user_logout,name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import product
from django.contrib.auth.models import User

class cart(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class order(models.Model):
     product=models.ForeignKey(product,on_delete=models.CASCADE)
     user = models.ForeignKey(User, on_delete=models.CASCADE)
     no_of_items=models.IntegerField()
     order_date=models.DateTimeField(auto_now_add=True)
     address=models.TextField()
     phone=models.BigIntegerField()
     order_status=models.CharField(max_length=30,default='pending')
     delivery_status=models.CharField(max_length=30,default='pending')

     def __str__(self):
         return self.user.username

class account(models.Model):
    acctnum=models.BigIntegerField()
    accttype=models.CharField(max_length=30)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class category(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField()
    image=models.ImageField(upload_to='media/images',null=True,blank=True)

    def __str__(self):
        return self.name

class product(models.Model):
    name = models.CharField(max_length=50)
    desc = models.TextField()
    image = models.ImageField(upload_to='media/images', null=True, blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from shop. models import product
from .models import cart,account,order
from django.http import HttpResponse

# Create your views here.

@login_required
def cartview(request):
    u=request.user
    c=cart.objects.filter(user=u)
    total=0
    for i in c:
        total=total+i.quantity*i.product.price
    return render(request,'addtocart.html',{'c':c,'total':total})
@login_required
def add_cart(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart_obj=cart.objects.get(user=u,product=p)
        if(p.stock>0):
            Cart_obj.quantity+=1
            Cart_obj.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock>0):
            Cart_obj=cart.objects.create(product=p,user=u,quantity=1)
            Cart_obj.save()
            p.stock-=1
            p.save()
    return cartview(request)

def cart_remove(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart= cart.objects.get(user=u, product=p)
        if (Cart.quantity > 1):
            Cart.quantity -= 1
            Cart.save()
            p.stock += 1
            p.save()

        else:
            Cart.delete()
            p.stock +=1
    except:
        pass
    return cartview(request)


def full_remove(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart=cart.objects.get(user=u,product=p)
        Cart.delete()
        p.stock += Cart.quantity
        p.save()
    except:
        pass
    return cartview(request)
def orderform(request):
    if(request.method=='POST'):
        a=request.POST['a']
        p=request.POST['p']
        ac=request.POST['ac']
        u=request.user
        c=cart.objects.filter(user=u)
        total=0
        for i in c:
            total=total+i.quantity*i.product.price
        try:
            an=account.objects.get(acctnum=ac)
            if(an.amount >= total):
                an.amount=an.amount-total
                an.save()
                for i in c:
                    b=order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status='paid')
                    b.save()
                c.delete()
                msg="Order Placed Successfully"
                return render(request,'orderdetail.html',{'message':msg})
            else:
                msg="Insufficient amount .You can't place order"
                return render(request,'orderdetail.html',{'message':msg})
        except:
            pass

    return render(request,'orderform.html',)

def Myorder(request):
    u=request.user
    b=order.objects.filter(user=u)
    return render(request,'orderview.html',{'c':b,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q

def searchproducts(request):
    p=None
    q=''
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            p=product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,'search.html',{'p':p,'q':q})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import category,product
# for displaying all categories
def allcategories(request):
    b=category.objects.all()
    return render(request,'category.html',{'b':b})

def allproducts(request,n):
    b=category.objects.get(id=n)
    c=product.objects.filter(category=b)
    return render(request,'product.html',{'b':b,'c':c})

def showdetail(request,n):
    p=product.objects.get(id=n)
    return render(request,'detail.html',{'p':p})
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        c=request.POST['c']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        if(c==p):
          b=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
          b.save()
          return redirect('shop:category1')
        else:
            return HttpResponse("Passwords are not same")
    return render(request,'Register.html',)

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:category1')
        else:
            return HttpResponse('Invalid Credentials')

    return render(request,'login.html')
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/Register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register Page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div style="background-image:url('{% static "images/formbck.jpg" %}');background-size:cover;background-size:100%100%;background-attachment:fixed;">
<h1 class="text-center">Please Sign Up</h1>
<hr class="w-25 mx-auto border border-2 border-dark">
<div class="mx-auto">
<form method="POST" enctype="multipart/form-data" class="w-25 mb-5 mx-auto">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
   <div class="mb-3">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="c">
  </div>
     <div class="mb-3">
    <label  class="form-label">E-mail</label>
    <input type="email" class="form-control" name="e">
  </div>
   <div class="mb-3">
    <label  class="form-label">First Name</label>
    <input type="text" class="form-control" name="f">
  </div>
   <div class="mb-3">
    <label  class="form-label">Last Name</label>
    <input type="text" class="form-control" name="l">
  </div>
  <button class="button-29" role="button">Register Now</button>
</form>
    </div>

<br>
    </div>


{% endblock %}

ecommerce/templates/addtocart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Cart page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div class="container-fluid mt-3">
    <h4 class="text-center">Shopping cart</h4>
    <div class="row">

        <div class="col-md-8">

            <table class="table table-bordered border-dark">
                <tr>
                    <th colspan="6">Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                   <td><img src="{{ i.product.image.url }}" height="150px;" width="150px;"></td>
                    <td><b>{{i.product.name}}</b></td>
                    <td>Product ID: {{i.product.id}}<br>
                    Quantity: {{i.quantity}}
                    Unit Price: {{i}}</td>
                    <td>Subtotal:{{i.subtotal}}</td>

                    <td>
                         {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.id %}" ><i class="fa-solid fa-circle-plus h4 text-sucess"></i></a>
                        <a href="{% url 'cart:cartremove' i.product.id %}"> <i class="fa-solid fa-circle-minus h4 text-danger"></i></a><br>
                        <a href="{% url 'cart:delete' i.product.id %}"> <i class="fa-solid fa-trash-can h4 text-warning"></i></a>
                        {% else %}
                          <a href="{% url 'cart:cartremove' i.product.id %}"> <i class="fa-solid fa-circle-minus h4 text-danger"></i></a><br>
                        <a href="{% url 'cart:delete' i.product.id %}"> <i class="fa-solid fa-trash-can h4 text-warning"></i></a>
                        {% endif %}


                    </td>
                </tr>
                {% endfor %}
            </table>

        </div>

        <div class="col-md-4">

            <table class="table table-bordered border-dark">
                <tr>
                    <th colspan="4">Check Out</th>
                </tr>
                <tr>
                    <td colspan="4">TOTAL AMOUNT: {{total}}</td>
                </tr>
            </table>
            <a class="btn btn-danger" href="{% url 'cart:order' %}">Place Order</a>
            <a class="btn btn-info" href="{% url 'shop:category1' %}">Continue Shopping</a>

        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxanium:wght@200..800&family=Stardos+Stencil:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" >
</head>
<body>
<header>
<center>
<!--<img  src="{% static 'images/Logo.png' %}" height="150px" width="150px">-->
</center>

<nav class="navbar navbar-expand-lg navbar-light bg-secondary" style="position:fixed;width:100%;z-index:1;">
    <img  src="{% static 'images/Logo.png' %}" height="60px;" width="60px;">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold nf " href="#" style="font-size:25px;">CARTIFY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:category1' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:Myorder' %}">Your Orders</a>
        </li>
          {% if user.is_superuser != True %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview'  %}"><i class="fa-solid fa-cart-shopping"><sup class="text-danger">{{count}}</sup></i></a>
         </li>
          {% endif %}

{% else %}
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:searchproducts' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-danger btn-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}

<footer class="bg-secondary text-center" >
    <p class="mt-3"><i class="fa-regular fa-copyright"></i>2024 Cartify private ltd. All rights reserved</p>
</footer>


</body>
</html>

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Category page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div class="container-fluid mt-3">
<img src="{%static 'images/banner.jpg' %}" width="100%" height="400px;" style="border-radius:10px;">
</div>
<section class="mt-3" style="margin-bottom:100px;">
    <h1 class="text-center">Collections</h1>
    <p>Contrary to popular belief, Lorem Ipsum is not simply random text.
        It has roots in a piece of classical Latin literature from 45 BC,
        making it over 2000 years old. Richard McClintock,
        a Latin professor at Hampden-Sydney College in Virginia, looked u
        one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage</p>
</section>
<section class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in b %}
        <div class="col-md-3">


        <div class="card mt-3" style="width: 18rem;">
            <img src="{{ i.image.url }}" class="card-img-top p-2 " alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text"></p>
                 <a href="{% url 'shop:products' i.id%}" class="btn btn-primary">Products</a>
            </div>
        </div>

        </div>
        {% endfor %}
    </div>

</section>



{% endblock %}

ecommerce/templates/detail.html
{%extends 'base.html' %}
{% load static %}
{% block title %}
Detail page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div class="container-fluid mt-3">
    <div class="row">

        <div class="col-md-6">
            <img src="{{p.image.url}}" style="border-radius:10px;" width="100%" height="400px;">
        </div>

        <div class="col-md-6">
            <h3>{{p.name}}</h3>
            <hr width="30%">
            <p>{{p.desc}}</p>
            <h4>Price : ₹{{p.price}}</h4>
            <p>Available stock : {{p.stock}}</p>
            {% if user.is_superuser == True %}

            {% if p.stock > 0 %}
            <h3 class="text-success">Product in stock </h3>
            <a href="{% url 'admin:index'  %}" class="btn btn-primary">Add stock</a>
            {% else %}
            <h3 class="text=danger">Product Out of stock </h3>
            <a href="{% url 'admin:index' %}" class="btn btn-primary">Add stock</a>
            {% endif %}

            {% else %}
            {% if p.stock > 0 %}
            <a href="{% url 'cart:addtocart' p.id %}" class="btn btn-primary">Add to cart</a><a href="" class="btn btn-info ms-2">Buy now</a>
            {% else %}
            <h3 class="text-danger">Out Of Stock!!!</h3>
            {% endif %}

            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register Page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<!--<div style="background-image:url('{% static "images/formbck.jpg" %}');background-size:cover;height:500px;background-size:100%100%;background-attachment:fixed;">-->
<!--<h1 class="text-center">Login</h1>-->
<!--<form method="POST" class="w-25 mx-auto">-->
<!--    {% csrf_token %}-->
<!--  <div class="mb-3">-->
<!--    <label class="form-label">Username</label>-->
<!--    <input type="text" class="form-control" name="u">-->
<!--  <div class="mb-3">-->
<!--    <label class="form-label">Password</label>-->
<!--    <input type="password" class="form-control" name="p">-->
<!--  </div>-->
<!--      <button type="submit" class="btn btn-primary">Submit</button>-->
<!--</form>-->
<!--</div>-->
<div class="container mt-1 mt-4" onclick="onclick">
    <div class="row">
        <div class="col-md-12">
  <div class="top"></div>
  <div class="bottom"></div>
  <div class="center">
      <form method="POST">
          {% csrf_token %}
    <h2 class="text-center">Please Sign In</h2>
    <input type="text" placeholder="Username" name="u"/>
    <input type="password" placeholder="password" name="p"/>
    <input type="submit"/>
          </form>
  </div>
        </div>
        </div>
</div>



{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% block content%}
<br>
<br>
<br>
<div class="container-fluid mt-5">
    <h1 class="text-center"><i class="fa-regular fa-circle-check"></i></h1>
<h3 class="text-center fw-bold">{{message}}</h3>
<h6 class="text-center">Thank you for choosing us</h6>
    <h5 class="text-center"><a href="{%url 'shop:category1' %}" class="btn btn-secondary">Continue Shopping</a></h5>
    </div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
order page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div style="background-image:url('{% static "images/formbck.jpg" %}');background-size:cover;height:500px;background-size:100%100%;background-attachment:fixed;">
<form method="POST" class="w-25 mx-auto text-center">
    <h1 class="text-center">Order Page</h1>
    <hr class=" border border-2 border-dark">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label fw-bold">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter address">
  <div class="mb-3">
    <label class="form-label fw-bold mt-3 ">Phone</label>
    <input type="number" class="form-control" name="p" placeholder="Enter phone number">
  </div>
  <div class="mb-3">
    <label class="form-label fw-bold">Account number</label>
    <input type="number" class="form-control" name="ac" placeholder="Enter account number">
  </div>
      <button type="submit" class="btn btn-primary">Place Order</button>
</form>
</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% block content%}
<br>
<br>
<br>
<div class="container-fluid">
    <div class="row">
        {% for i in c %}
        <h3 class="mt-3 text-center" style="font-family:sans serif;"> Name of Customer: {{u}}</h3>
        <div class="col-md-6 mt-2">
            <img src="{{i.product.image.url}}" width="100%" height="400px" style="border-radius:12px;">
        </div>
        <div class="col-md-6">
            <h2 class="text-center" style="font-family:sans serif;"> Details</h2>
            <hr class="w-25 mx-auto border border-2 border-dark">
            <h5 style="font-family:sans serif;"><b>Product name: </b>{{i.product.name}}</h5>
            <h5 style="font-family:sans serif;"><b>Price: </b>₹{{i.product.price}}</h5>
            <h5 style="font-family:sans serif;"><b>Delivery Address: </b>{{i.address}}</h5>
            <h5 style="font-family:sans serif;"><b>Phone : </b>{{i.phone}}</h5>
            <h5 style="font-family:sans serif;"><b>No of Items : </b>{{i.no_of_items}}</h5>
            <h5 style="font-family:sans serif;" class="fst-italic"><b>Ordered On : </b>{{i.order_date}}</h5>
            <h5 style="font-family:sans serif;" class="fst-italic"><b>Delivery Status : </b>{{i.delivery_status}}</h5>
        </div>
        {% endfor %}
    </div>
</div>
<br>
<br>
<br>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Category page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<div class="container-fluid mt-3">
<img src="{{b.image.url}}" width="100%" height="400px;" style="border-radius:10px;">
</div>
<section class="mt-3" style="margin-bottom:100px;">
    <h1 class="text-center">{{b.name}}</h1>
    <p>{{b.desc}}</p>
</section>
<section class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-md-3">


        <div class="card mt-3" style="width: 18rem;">
            <img src="{{ i.image.url }}" class="card-img-top p-3" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text"></p>
                 <p>Price : ₹{{i.price}}</p>
                <a href="{% url 'shop:details' i.id%}" class="btn btn-primary">Show details</a>

            </div>
        </div>

        </div>
        {% endfor %}
    </div>

</section>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Search Page
{% endblock %}
{% block content %}
<br>
<br>
<br>
<p class="text-center">You have searched for <span class="text-info">{{q}}</span></p>
<section class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-md-3">


        <div class="card mt-3" style="width: 18rem;">
            <img src="{{ i.image.url }}" class="card-img-top p-3" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text"></p>
                 <p>Price : ₹{{i.price}}</p>
                <a href="{% url 'shop:details' i.id%}" class="btn btn-primary">Show details</a>

            </div>
        </div>
{% empty %}
            <h5 class="text-danger text-center">No results found</h5>
        </div>
        {% endfor %}
    </div>

</section>

{% endblock %}